import type { Metadata } from "next";
import { Inter, Orbitron, Fira_Sans ,Open_Sans } from "next/font/google";
import "./globals.css";

const orbitron = Orbitron({ subsets: ["latin"], variable: "--font-orbitron" });
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700;800&display=swap" rel="stylesheet" />

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "300", "500","600"],
  variable: "--font-open-sans",
});
const inter = Fira_Sans({
  subsets: ["latin"],
  weight: ["400", "100", "200", "300", "500"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${orbitron.variable} ${inter.variable} ${openSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
